[package]
name = "sciKernel"
version = "0.1.0"
authors = ["xieguigang <xie.guigang@gcmodeller.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="sciKernel"
crate-type=["dylib"]
path="src/lib.rs"